<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Enter</title>
</head>
<body>
<form action="/signIn" method="post">
    <input name="email" placeholder="Email">
    <input name="password" type="password" placeholder="Password">
    <input type="submit" value="Sign In">
</form>
<p></p>
<a href="http://localhost:8080/signUp">Create your account</a>
</body>
</html>