<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registration</title>
</head>
<body>
<div>
    <form action="/signUp" method="post">
        <input name="firstName" placeholder="Имя">
        <input name="lastName" placeholder="Фамилия">
        <input name="email" placeholder="Email">
        <input name="password" type="password" placeholder="Password">
        <input type="submit" value="Sign Up">
    </form>
</div>
</body>
</html>